- id: '1530945123989'
  alias: Backlight On
  trigger:
  - entity_id: binary_sensor.workstation
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.desktop_backlight
    service: light.turn_on
- id: '1530945171790'
  alias: Backlight Off
  trigger:
  - entity_id: binary_sensor.workstation
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.desktop_backlight
    service: light.turn_off
