homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.3878
  longitude: -80.4296
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_password
#  ssl_certificate: /etc/letsencrypt/live/nnarain.duckdns.org/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/nnarain.duckdns.org/privkey.pem
#  base_url: nnarain.duckdns.org

# DuckDNS
duckdns:
  domain: nnarain
  access_token: !secret duckdns_access_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# MQTT Setup
mqtt:
  broker: mosquitto

# Sensors
sensor:
  # Weather prediction
  - platform: yr

  # Home server stats
  - platform: mqtt
    name: myhome_stats_cpu
    state_topic: /home/home/stats/cpu
    unit_of_measurement: "percent"
  - platform: mqtt
    name: myhome_stats_memory
    state_topic: /home/home/stats/memory
    unit_of_measurement: "percent"
  - platform: mqtt
    name: myhome_stats_temperature
    state_topic: /home/home/stats/temperature
    unit_of_measurement: C

  # Media Center Stats
  - platform: mqtt
    name: mediacenter_stats_cpu
    state_topic: /home/mediacenter/stats/cpu
    unit_of_measurement: "percent"
  - platform: mqtt
    name: mediacenter_stats_memory
    state_topic: /home/mediacenter/stats/memory
    unit_of_measurement: "percent"
  - platform: mqtt
    name: mediacenter_stats_temperature
    state_topic: /home/mediacenter/stats/temperature
    unit_of_measurement: C

  - platform: command_line
    name: SSL vert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/nnarain.duckdns.org/cert.pem | awk '{print $NF}'"

# Shell command for SSL cert renewal
#shell_command:
#  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges tls-sni-01 --tls-sni-01-port 8123 --pre-hook "sudo systemctl stop home-assistant@pi.service" --post-hook "sudo systemctl start home-assistant@pi.service"

# Text to speech
tts:
  - platform: google

# TP Link Devices
tplink:
  discovery: false
  switch:
    - host: 192.168.0.11
    - host: 192.168.0.12

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
